import type { ChainConfig, ChainId } from "@/types/chain";

export const CHAINS: Record<ChainId, ChainConfig> = {
  mcdonalds: {
    id: "mcdonalds",
    name: "McDonald's",
    shortName: "McD",
    logo: "/chains/mcdonalds.svg",
    color: "#FFC72C",
    pointsName: "MyMcDonald's points",
    pointsSymbol: "pts",
    pointsPerDollar: 100,
    valuePerPoint: 0.005,
    appDeepLink: "https://www.mcdonalds.com/us/en-us/mymcdonalds.html",
  },
  chickfila: {
    id: "chickfila",
    name: "Chick-fil-A",
    shortName: "CFA",
    logo: "/chains/chickfila.svg",
    color: "#E51636",
    pointsName: "Chick-fil-A points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.05,
    appDeepLink: "https://www.chick-fil-a.com/one",
  },
  wendys: {
    id: "wendys",
    name: "Wendy's",
    shortName: "Wendy's",
    logo: "/chains/wendys.svg",
    color: "#00A3E0",
    pointsName: "Wendy's Rewards",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.025,
    appDeepLink: "https://www.wendys.com/rewards",
  },
  tacobell: {
    id: "tacobell",
    name: "Taco Bell",
    shortName: "TB",
    logo: "/chains/tacobell.svg",
    color: "#702082",
    pointsName: "Taco Bell Rewards",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.02,
    appDeepLink: "https://www.tacobell.com/rewards",
  },
  burgerking: {
    id: "burgerking",
    name: "Burger King",
    shortName: "BK",
    logo: "/chains/burgerking.svg",
    color: "#FF8732",
    pointsName: "Royal Perks crowns",
    pointsSymbol: "crowns",
    pointsPerDollar: 10,
    valuePerPoint: 0.01,
    appDeepLink: "https://www.bk.com/rewards",
  },
  popeyes: {
    id: "popeyes",
    name: "Popeyes",
    shortName: "Popeyes",
    logo: "/chains/popeyes.svg",
    color: "#F15A22",
    pointsName: "Popeyes Rewards",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.02,
    appDeepLink: "https://www.popeyes.com/rewards",
  },
  subway: {
    id: "subway",
    name: "Subway",
    shortName: "Subway",
    logo: "/chains/subway.svg",
    color: "#008C15",
    pointsName: "MVP tokens",
    pointsSymbol: "tokens",
    pointsPerDollar: 4,
    valuePerPoint: 0.025,
    appDeepLink: "https://www.subway.com/en-US/Rewards",
  },
  dunkin: {
    id: "dunkin",
    name: "Dunkin'",
    shortName: "Dunkin'",
    logo: "/chains/dunkin.svg",
    color: "#FF671F",
    pointsName: "DD Perks points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.005,
    appDeepLink: "https://www.dunkindonuts.com/en/dd-perks",
  },
  starbucks: {
    id: "starbucks",
    name: "Starbucks",
    shortName: "SBX",
    logo: "/chains/starbucks.svg",
    color: "#00704A",
    pointsName: "Stars",
    pointsSymbol: "★",
    pointsPerDollar: 2,
    valuePerPoint: 0.0125,
    appDeepLink: "https://www.starbucks.com/rewards",
  },
};

export const CHAIN_IDS = Object.keys(CHAINS) as ChainId[];

export function getChain(slug: string): ChainConfig | undefined {
  return CHAINS[slug as ChainId];
}
