import type { ChainConfig, ChainId } from "@/types/chain";

// valuePerPoint is the conservative dollar value of a single point at a
// *typical mid-tier* redemption — not the cherry-picked best case. The
// dashboard card multiplies this by the user's balance to show an estimated
// dollar value; if we set it to the best-case redemption the number would
// chronically overpromise. Numbers below are derived from each chain's
// current reward menu (~late 2025); revisit when chains change tiers.
export const CHAINS: Record<ChainId, ChainConfig> = {
  mcdonalds: {
    id: "mcdonalds",
    name: "McDonald's",
    shortName: "McD",
    logo: "/chains/mcdonalds.svg",
    domain: "mcdonalds.com",
    color: "#FFC72C",
    pointsName: "MyMcDonald's points",
    pointsSymbol: "pts",
    pointsPerDollar: 100,
    // 6,000 pts → ~$5.99 sandwich tier ≈ 0.1¢/pt
    valuePerPoint: 0.001,
    appDeepLink: "https://www.mcdonalds.com/us/en-us/mymcdonalds.html",
    // MyMcDonald's points are only visible in the mobile app — the web
    // rewards page doesn't display a balance.
    appOnly: true,
  },
  chickfila: {
    id: "chickfila",
    name: "Chick-fil-A",
    shortName: "CFA",
    logo: "/chains/chickfila.svg",
    domain: "chick-fil-a.com",
    color: "#E51636",
    pointsName: "Chick-fil-A points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    // 350 pts → ~$3.50 small item / 550 pts → ~$5.99 sandwich ≈ 1¢/pt
    valuePerPoint: 0.01,
    appDeepLink: "https://www.chick-fil-a.com/one",
  },
  wendys: {
    id: "wendys",
    name: "Wendy's",
    shortName: "Wendy's",
    logo: "/chains/wendys.svg",
    domain: "wendys.com",
    color: "#00A3E0",
    pointsName: "Wendy's Rewards",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    // 2,000 pts → $5 free item ≈ 0.25¢/pt
    valuePerPoint: 0.0025,
    appDeepLink: "https://www.wendys.com/rewards",
  },
  tacobell: {
    id: "tacobell",
    name: "Taco Bell",
    shortName: "TB",
    logo: "/chains/tacobell.svg",
    domain: "tacobell.com",
    color: "#702082",
    pointsName: "Taco Bell Rewards",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    // 250 pts → ~$1.49 / 750 pts → ~$5 combo ≈ 0.5¢/pt
    valuePerPoint: 0.005,
    appDeepLink: "https://www.tacobell.com/rewards",
    // TB only exposes points in the mobile app — even after registering, the
    // web rewards page says "Redeem exclusive rewards only on the app."
    appOnly: true,
  },
  burgerking: {
    id: "burgerking",
    name: "Burger King",
    shortName: "BK",
    logo: "/chains/burgerking.svg",
    domain: "bk.com",
    color: "#FF8732",
    pointsName: "Royal Perks crowns",
    pointsSymbol: "crowns",
    pointsPerDollar: 10,
    // 500 crowns → ~$1.99 cookie / 1,500 crowns → ~$5 sandwich ≈ 0.35¢/crown
    valuePerPoint: 0.0035,
    appDeepLink: "https://www.bk.com/rewards",
  },
  popeyes: {
    id: "popeyes",
    name: "Popeyes",
    shortName: "Popeyes",
    logo: "/chains/popeyes.svg",
    domain: "popeyes.com",
    color: "#F15A22",
    pointsName: "Popeyes Rewards",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    // 1,000 pts → ~$2 cookie / 2,200 pts → ~$4.99 sandwich ≈ 0.22¢/pt
    valuePerPoint: 0.0022,
    appDeepLink: "https://www.popeyes.com/rewards",
  },
  subway: {
    id: "subway",
    name: "Subway",
    shortName: "Subway",
    logo: "/chains/subway.svg",
    domain: "subway.com",
    color: "#008C15",
    pointsName: "MVP tokens",
    pointsSymbol: "tokens",
    pointsPerDollar: 4,
    // 200 tokens → ~$2 toward sub ≈ 1¢/token (MVP cash-equivalent program)
    valuePerPoint: 0.01,
    appDeepLink: "https://www.subway.com/en-US/Rewards",
    // subway.com is fronted by Akamai and frequently fast-fails residential
    // IPs with "Access Denied" — even after a valid signin. Until that's
    // reliable we surface manual entry only.
    appOnly: true,
  },
  dunkin: {
    id: "dunkin",
    name: "Dunkin'",
    shortName: "Dunkin'",
    logo: "/chains/dunkin.svg",
    domain: "dunkindonuts.com",
    color: "#FF671F",
    pointsName: "DD Perks points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    // 700 pts → ~$3.50 drink / 1,000 pts → ~$5 ≈ 0.5¢/pt
    valuePerPoint: 0.005,
    appDeepLink: "https://www.dunkindonuts.com/en/dd-perks",
  },
  starbucks: {
    id: "starbucks",
    name: "Starbucks",
    shortName: "SBX",
    logo: "/chains/starbucks.svg",
    domain: "starbucks.com",
    color: "#00704A",
    pointsName: "Stars",
    pointsSymbol: "★",
    pointsPerDollar: 2,
    // 200 stars → ~$3.50 drip coffee / 400 stars → ~$5.50 handcrafted ≈ 1.4¢/star
    valuePerPoint: 0.014,
    appDeepLink: "https://www.starbucks.com/rewards",
  },
  chipotle: {
    id: "chipotle",
    name: "Chipotle",
    shortName: "Chipotle",
    logo: "/chains/chipotle.svg",
    domain: "chipotle.com",
    color: "#A81612",
    pointsName: "Chipotle Rewards points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    // 1,300 pts → ~$10 entree ≈ 0.77¢/pt
    valuePerPoint: 0.0077,
    appDeepLink: "https://www.chipotle.com/rewards",
  },
  pancheros: {
    id: "pancheros",
    name: "Pancheros",
    shortName: "Pancheros",
    logo: "/chains/pancheros.svg",
    domain: "pancheros.com",
    color: "#ED1C24",
    pointsName: "Pancheros Rewards points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.01,
    appDeepLink: "https://www.pancheros.com/rewards",
  },
  dairyqueen: {
    id: "dairyqueen",
    name: "Dairy Queen",
    shortName: "DQ",
    logo: "/chains/dairyqueen.svg",
    domain: "dairyqueen.com",
    color: "#ED1C24",
    pointsName: "DQ Rewards points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.005,
    appDeepLink: "https://www.dairyqueen.com/en-us/account/rewards/",
  },
  culvers: {
    id: "culvers",
    name: "Culver's",
    shortName: "Culver's",
    logo: "/chains/culvers.svg",
    domain: "culvers.com",
    color: "#1B3F8B",
    pointsName: "Culver's Rewards points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.005,
    appDeepLink: "https://www.culvers.com/rewards",
  },
  jimmyjohns: {
    id: "jimmyjohns",
    name: "Jimmy John's",
    shortName: "JJ",
    logo: "/chains/jimmyjohns.svg",
    domain: "jimmyjohns.com",
    color: "#ED1C24",
    pointsName: "Freaky Fast Rewards points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.01,
    appDeepLink: "https://www.jimmyjohns.com/rewards",
  },
  buffalowildwings: {
    id: "buffalowildwings",
    name: "Buffalo Wild Wings",
    shortName: "BWW",
    logo: "/chains/buffalowildwings.svg",
    domain: "buffalowildwings.com",
    color: "#FAB31E",
    pointsName: "Blazin' Rewards points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.01,
    appDeepLink: "https://www.buffalowildwings.com/account/rewards/",
  },
  kfc: {
    id: "kfc",
    name: "KFC",
    shortName: "KFC",
    logo: "/chains/kfc.svg",
    domain: "kfc.com",
    color: "#F40027",
    pointsName: "KFC Rewards points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.01,
    appDeepLink: "https://www.kfc.com/dashboard",
  },
  pandaexpress: {
    id: "pandaexpress",
    name: "Panda Express",
    shortName: "Panda",
    logo: "/chains/pandaexpress.svg",
    domain: "pandaexpress.com",
    color: "#D81E05",
    pointsName: "Panda Rewards points",
    pointsSymbol: "pts",
    pointsPerDollar: 10,
    valuePerPoint: 0.01,
    appDeepLink: "https://www.pandaexpress.com/myrewards/earn",
  },
};

export const CHAIN_IDS = Object.keys(CHAINS) as ChainId[];

export function getChain(slug: string): ChainConfig | undefined {
  return CHAINS[slug as ChainId];
}
