import { PrismaClient, RedemptionCategory } from "@prisma/client";

const prisma = new PrismaClient();

interface RedemptionSeed {
  itemName: string;
  pointsCost: number;
  retail: number;
  category: RedemptionCategory;
}

interface ChainSeed {
  slug: string;
  name: string;
  logo: string;
  color: string;
  pointsName: string;
  websiteUrl: string;
  appDeepLink?: string;
  scrapingEnabled: boolean;
  redemptions: RedemptionSeed[];
}

function centsPerPoint(retail: number, points: number): number {
  return Math.round((retail / points) * 100 * 10000) / 10000;
}

const CHAINS: ChainSeed[] = [
  {
    slug: "mcdonalds",
    name: "McDonald's",
    logo: "/chains/mcdonalds.svg",
    color: "#FFC72C",
    pointsName: "points",
    websiteUrl: "https://www.mcdonalds.com",
    appDeepLink: "mcdonalds://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Vanilla Cone", pointsCost: 1500, retail: 1.49, category: "DESSERT" },
      { itemName: "Hash Browns", pointsCost: 1500, retail: 1.79, category: "SIDE" },
      { itemName: "Small French Fries", pointsCost: 1500, retail: 2.29, category: "SIDE" },
      { itemName: "Cheeseburger", pointsCost: 1500, retail: 2.49, category: "ENTREE" },
      { itemName: "McChicken", pointsCost: 1500, retail: 2.49, category: "ENTREE" },
      { itemName: "Sausage McMuffin", pointsCost: 3000, retail: 3.19, category: "ENTREE" },
      { itemName: "Medium French Fries", pointsCost: 3000, retail: 3.29, category: "SIDE" },
      { itemName: "6-pc Chicken McNuggets", pointsCost: 3000, retail: 3.49, category: "ENTREE" },
      { itemName: "McFlurry", pointsCost: 4500, retail: 3.99, category: "DESSERT" },
      { itemName: "Egg McMuffin", pointsCost: 4500, retail: 4.49, category: "ENTREE" },
      { itemName: "Filet-O-Fish", pointsCost: 4500, retail: 4.99, category: "ENTREE" },
      { itemName: "Happy Meal", pointsCost: 6000, retail: 4.99, category: "COMBO" },
      { itemName: "10-pc Chicken McNuggets", pointsCost: 6000, retail: 5.49, category: "ENTREE" },
      { itemName: "Big Mac", pointsCost: 6000, retail: 5.69, category: "ENTREE" },
      { itemName: "Quarter Pounder with Cheese", pointsCost: 6000, retail: 5.99, category: "ENTREE" },
    ],
  },
  {
    slug: "chickfila",
    name: "Chick-fil-A",
    logo: "/chains/chickfila.svg",
    color: "#DD0031",
    pointsName: "points",
    websiteUrl: "https://www.chick-fil-a.com",
    appDeepLink: "cfaone://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Chocolate Chunk Cookie", pointsCost: 250, retail: 1.69, category: "DESSERT" },
      { itemName: "Small Waffle Potato Fries", pointsCost: 350, retail: 2.39, category: "SIDE" },
      { itemName: "Hash Browns", pointsCost: 450, retail: 2.59, category: "SIDE" },
      { itemName: "Iced Coffee", pointsCost: 450, retail: 2.99, category: "DRINK" },
      { itemName: "Frosted Lemonade", pointsCost: 650, retail: 4.39, category: "DRINK" },
      { itemName: "Chicken Biscuit", pointsCost: 700, retail: 3.55, category: "ENTREE" },
      { itemName: "Greek Yogurt Parfait", pointsCost: 750, retail: 4.19, category: "DESSERT" },
      { itemName: "Chick-n-Strips (3 ct)", pointsCost: 850, retail: 5.85, category: "ENTREE" },
      { itemName: "Mac & Cheese (medium)", pointsCost: 950, retail: 4.49, category: "SIDE" },
      { itemName: "Chick-fil-A Chicken Sandwich", pointsCost: 950, retail: 5.85, category: "ENTREE" },
      { itemName: "8-ct Nuggets", pointsCost: 950, retail: 5.99, category: "ENTREE" },
      { itemName: "Spicy Deluxe Sandwich", pointsCost: 1050, retail: 6.45, category: "ENTREE" },
      { itemName: "12-ct Nuggets", pointsCost: 1350, retail: 8.19, category: "ENTREE" },
      { itemName: "Cobb Salad", pointsCost: 1400, retail: 9.65, category: "ENTREE" },
      { itemName: "Chick-fil-A Deluxe Meal", pointsCost: 1700, retail: 11.49, category: "COMBO" },
    ],
  },
  {
    slug: "wendys",
    name: "Wendy's",
    logo: "/chains/wendys.svg",
    color: "#E2203D",
    pointsName: "points",
    websiteUrl: "https://www.wendys.com",
    appDeepLink: "wendys://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Jr. Frosty", pointsCost: 50, retail: 0.99, category: "DESSERT" },
      { itemName: "4-pc Nuggets", pointsCost: 150, retail: 1.99, category: "SIDE" },
      { itemName: "Small Fries", pointsCost: 200, retail: 2.59, category: "SIDE" },
      { itemName: "Small Chili", pointsCost: 250, retail: 2.49, category: "SIDE" },
      { itemName: "4-pc Spicy Nuggets", pointsCost: 350, retail: 2.99, category: "SIDE" },
      { itemName: "Medium Frosty", pointsCost: 400, retail: 2.49, category: "DESSERT" },
      { itemName: "Jr. Bacon Cheeseburger", pointsCost: 400, retail: 3.29, category: "ENTREE" },
      { itemName: "Crispy Chicken Sandwich", pointsCost: 500, retail: 3.99, category: "ENTREE" },
      { itemName: "Dave's Single", pointsCost: 600, retail: 5.99, category: "ENTREE" },
      { itemName: "10-pc Nuggets", pointsCost: 700, retail: 4.99, category: "ENTREE" },
      { itemName: "Spicy Chicken Sandwich", pointsCost: 800, retail: 6.79, category: "ENTREE" },
      { itemName: "Dave's Double", pointsCost: 1000, retail: 7.29, category: "ENTREE" },
      { itemName: "Baconator", pointsCost: 1600, retail: 8.79, category: "ENTREE" },
      { itemName: "Pretzel Baconator", pointsCost: 1700, retail: 9.29, category: "ENTREE" },
      { itemName: "Spicy Chicken Combo", pointsCost: 2000, retail: 10.49, category: "COMBO" },
    ],
  },
  {
    slug: "burgerking",
    name: "Burger King",
    logo: "/chains/burgerking.svg",
    color: "#D62300",
    pointsName: "crowns",
    websiteUrl: "https://www.bk.com",
    appDeepLink: "burgerking://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Soft Serve Cone", pointsCost: 250, retail: 1.49, category: "DESSERT" },
      { itemName: "Hash Browns", pointsCost: 500, retail: 2.49, category: "SIDE" },
      { itemName: "Small Fries", pointsCost: 750, retail: 2.79, category: "SIDE" },
      { itemName: "Small Onion Rings", pointsCost: 750, retail: 2.99, category: "SIDE" },
      { itemName: "Cheeseburger", pointsCost: 1000, retail: 2.29, category: "ENTREE" },
      { itemName: "Croissan'wich", pointsCost: 1200, retail: 3.59, category: "ENTREE" },
      { itemName: "Chicken Fries (9 pc)", pointsCost: 1200, retail: 4.19, category: "SIDE" },
      { itemName: "Whopper Jr.", pointsCost: 1500, retail: 3.99, category: "ENTREE" },
      { itemName: "Bacon Cheeseburger", pointsCost: 1800, retail: 3.99, category: "ENTREE" },
      { itemName: "Original Chicken Sandwich", pointsCost: 2000, retail: 5.49, category: "ENTREE" },
      { itemName: "Whopper", pointsCost: 2500, retail: 6.79, category: "ENTREE" },
      { itemName: "Impossible Whopper", pointsCost: 2700, retail: 7.29, category: "ENTREE" },
      { itemName: "Bacon King", pointsCost: 3000, retail: 8.49, category: "ENTREE" },
      { itemName: "Double Whopper", pointsCost: 3200, retail: 8.49, category: "ENTREE" },
      { itemName: "Whopper Meal", pointsCost: 4000, retail: 9.99, category: "COMBO" },
    ],
  },
  {
    slug: "tacobell",
    name: "Taco Bell",
    logo: "/chains/tacobell.svg",
    color: "#702082",
    pointsName: "points",
    websiteUrl: "https://www.tacobell.com",
    appDeepLink: "tacobell://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Cinnamon Twists", pointsCost: 250, retail: 1.49, category: "DESSERT" },
      { itemName: "Cheesy Roll-Up", pointsCost: 250, retail: 1.49, category: "SIDE" },
      { itemName: "Large Fountain Drink", pointsCost: 250, retail: 2.29, category: "DRINK" },
      { itemName: "Crunchy Taco", pointsCost: 500, retail: 1.99, category: "ENTREE" },
      { itemName: "Soft Taco", pointsCost: 500, retail: 1.99, category: "ENTREE" },
      { itemName: "Cheesy Fiesta Potatoes", pointsCost: 500, retail: 2.49, category: "SIDE" },
      { itemName: "Doritos Locos Taco", pointsCost: 750, retail: 2.79, category: "ENTREE" },
      { itemName: "Cheesy Bean & Rice Burrito", pointsCost: 750, retail: 2.49, category: "ENTREE" },
      { itemName: "Beefy 5-Layer Burrito", pointsCost: 750, retail: 3.49, category: "ENTREE" },
      { itemName: "Chalupa Supreme", pointsCost: 1000, retail: 4.99, category: "ENTREE" },
      { itemName: "Cheesy Gordita Crunch", pointsCost: 1000, retail: 4.79, category: "ENTREE" },
      { itemName: "Quesadilla", pointsCost: 1000, retail: 4.99, category: "ENTREE" },
      { itemName: "Crunchwrap Supreme", pointsCost: 1500, retail: 5.49, category: "ENTREE" },
      { itemName: "Nachos BellGrande", pointsCost: 1500, retail: 5.49, category: "ENTREE" },
      { itemName: "Grande Nachos Box", pointsCost: 2000, retail: 6.99, category: "COMBO" },
    ],
  },
  {
    slug: "popeyes",
    name: "Popeyes",
    logo: "/chains/popeyes.svg",
    color: "#FF7E1B",
    pointsName: "points",
    websiteUrl: "https://www.popeyes.com",
    appDeepLink: "popeyes://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Biscuit", pointsCost: 150, retail: 1.29, category: "SIDE" },
      { itemName: "Regular Side", pointsCost: 200, retail: 2.99, category: "SIDE" },
      { itemName: "Apple Pie", pointsCost: 300, retail: 1.99, category: "DESSERT" },
      { itemName: "4-pc Nuggets", pointsCost: 300, retail: 3.49, category: "SIDE" },
      { itemName: "Large Side", pointsCost: 350, retail: 3.99, category: "SIDE" },
      { itemName: "Red Beans & Rice (Large)", pointsCost: 350, retail: 3.99, category: "SIDE" },
      { itemName: "2-pc Signature Chicken", pointsCost: 400, retail: 4.49, category: "ENTREE" },
      { itemName: "3-pc Chicken Tenders", pointsCost: 500, retail: 5.99, category: "ENTREE" },
      { itemName: "Classic Chicken Sandwich", pointsCost: 800, retail: 5.99, category: "ENTREE" },
      { itemName: "Spicy Chicken Sandwich", pointsCost: 800, retail: 5.99, category: "ENTREE" },
      { itemName: "12-pc Nuggets", pointsCost: 900, retail: 7.99, category: "ENTREE" },
      { itemName: "8-pc Nuggets Combo", pointsCost: 1000, retail: 8.49, category: "COMBO" },
      { itemName: "3-pc Signature Chicken Combo", pointsCost: 1300, retail: 10.49, category: "COMBO" },
      { itemName: "5-pc Tenders Combo", pointsCost: 1500, retail: 11.99, category: "COMBO" },
      { itemName: "Family Feast (10-pc)", pointsCost: 2500, retail: 24.99, category: "COMBO" },
    ],
  },
  {
    slug: "subway",
    name: "Subway",
    logo: "/chains/subway.svg",
    color: "#008C15",
    pointsName: "tokens",
    websiteUrl: "https://www.subway.com",
    appDeepLink: "subway://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Cookie", pointsCost: 200, retail: 0.79, category: "DESSERT" },
      { itemName: "Chips", pointsCost: 200, retail: 1.99, category: "SIDE" },
      { itemName: "Bottled Water", pointsCost: 250, retail: 1.99, category: "DRINK" },
      { itemName: "Fountain Drink", pointsCost: 300, retail: 2.49, category: "DRINK" },
      { itemName: "Hash Browns", pointsCost: 300, retail: 1.99, category: "SIDE" },
      { itemName: "Mini Sub", pointsCost: 400, retail: 3.99, category: "ENTREE" },
      { itemName: "6-inch Sub", pointsCost: 600, retail: 5.99, category: "ENTREE" },
      { itemName: "Breakfast Wrap", pointsCost: 700, retail: 5.49, category: "ENTREE" },
      { itemName: "Footlong Dippers", pointsCost: 800, retail: 6.99, category: "SIDE" },
      { itemName: "Footlong Cookie", pointsCost: 800, retail: 5.49, category: "DESSERT" },
      { itemName: "Wrap", pointsCost: 1000, retail: 7.49, category: "ENTREE" },
      { itemName: "6-inch Combo (sub + chips + drink)", pointsCost: 1000, retail: 9.49, category: "COMBO" },
      { itemName: "Footlong Sub", pointsCost: 1200, retail: 9.99, category: "ENTREE" },
      { itemName: "Footlong Pro Sub (extra protein)", pointsCost: 1500, retail: 11.99, category: "ENTREE" },
      { itemName: "Footlong Combo (sub + chips + drink)", pointsCost: 1600, retail: 13.49, category: "COMBO" },
    ],
  },
  {
    slug: "dunkin",
    name: "Dunkin'",
    logo: "/chains/dunkin.svg",
    color: "#FF671F",
    pointsName: "points",
    websiteUrl: "https://www.dunkindonuts.com",
    appDeepLink: "dunkin://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Classic Donut", pointsCost: 150, retail: 1.49, category: "DESSERT" },
      { itemName: "Bagel with Cream Cheese", pointsCost: 250, retail: 2.49, category: "ENTREE" },
      { itemName: "Hash Browns", pointsCost: 300, retail: 1.99, category: "SIDE" },
      { itemName: "Medium Hot Coffee", pointsCost: 400, retail: 2.99, category: "DRINK" },
      { itemName: "Medium Iced Coffee", pointsCost: 450, retail: 3.29, category: "DRINK" },
      { itemName: "Medium Iced Latte", pointsCost: 500, retail: 3.79, category: "DRINK" },
      { itemName: "Donut + Medium Coffee Combo", pointsCost: 600, retail: 4.49, category: "COMBO" },
      { itemName: "Medium Hot Latte", pointsCost: 600, retail: 3.99, category: "DRINK" },
      { itemName: "Stuffed Biscuit Bites", pointsCost: 700, retail: 3.49, category: "SIDE" },
      { itemName: "Avocado Toast", pointsCost: 800, retail: 4.49, category: "ENTREE" },
      { itemName: "Medium Frozen Coffee", pointsCost: 800, retail: 4.99, category: "DRINK" },
      { itemName: "Iced Signature Latte", pointsCost: 900, retail: 5.49, category: "DRINK" },
      { itemName: "Wake-Up Wrap", pointsCost: 900, retail: 3.99, category: "ENTREE" },
      { itemName: "Sausage Egg & Cheese Sandwich", pointsCost: 1000, retail: 5.49, category: "ENTREE" },
      { itemName: "Box O' Joe", pointsCost: 1500, retail: 14.99, category: "DRINK" },
    ],
  },
  {
    slug: "starbucks",
    name: "Starbucks",
    logo: "/chains/starbucks.svg",
    color: "#006241",
    pointsName: "stars",
    websiteUrl: "https://www.starbucks.com",
    appDeepLink: "starbucks://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Extra Espresso Shot or Add-on", pointsCost: 25, retail: 0.95, category: "DRINK" },
      { itemName: "Brewed Hot Coffee (any size)", pointsCost: 100, retail: 3.45, category: "DRINK" },
      { itemName: "Hot Tea", pointsCost: 100, retail: 3.25, category: "DRINK" },
      { itemName: "Bakery Item", pointsCost: 100, retail: 3.95, category: "DESSERT" },
      { itemName: "Packaged Snack", pointsCost: 100, retail: 2.95, category: "SIDE" },
      { itemName: "Premium Bottled Drink", pointsCost: 200, retail: 4.25, category: "DRINK" },
      { itemName: "Oatmeal or Yogurt", pointsCost: 200, retail: 4.45, category: "ENTREE" },
      { itemName: "Grande Handcrafted Drink", pointsCost: 200, retail: 5.45, category: "DRINK" },
      { itemName: "Iced Latte (Grande)", pointsCost: 200, retail: 5.45, category: "DRINK" },
      { itemName: "Hot Breakfast Sandwich", pointsCost: 200, retail: 5.45, category: "ENTREE" },
      { itemName: "Frappuccino (Grande)", pointsCost: 200, retail: 5.95, category: "DRINK" },
      { itemName: "Protein Box", pointsCost: 300, retail: 7.95, category: "ENTREE" },
      { itemName: "Lunch Sandwich or Salad", pointsCost: 300, retail: 8.95, category: "ENTREE" },
      { itemName: "Bag of Whole Bean Coffee", pointsCost: 400, retail: 15.95, category: "OTHER" },
      { itemName: "Starbucks Merchandise or Mug", pointsCost: 400, retail: 16.95, category: "OTHER" },
    ],
  },
  {
    slug: "chipotle",
    name: "Chipotle",
    logo: "/chains/chipotle.svg",
    color: "#A81612",
    pointsName: "points",
    websiteUrl: "https://www.chipotle.com",
    appDeepLink: "chipotle://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Chips", pointsCost: 250, retail: 1.85, category: "SIDE" },
      { itemName: "Fountain Drink", pointsCost: 300, retail: 2.85, category: "DRINK" },
      { itemName: "Bottled Water", pointsCost: 300, retail: 2.65, category: "DRINK" },
      { itemName: "Chips & Salsa", pointsCost: 350, retail: 2.45, category: "SIDE" },
      { itemName: "Side of Queso", pointsCost: 400, retail: 2.50, category: "SIDE" },
      { itemName: "Chips & Guac", pointsCost: 550, retail: 3.95, category: "SIDE" },
      { itemName: "Side Salad", pointsCost: 600, retail: 4.25, category: "SIDE" },
      { itemName: "Large Chips & Large Guac", pointsCost: 800, retail: 6.50, category: "SIDE" },
      { itemName: "Kids Meal", pointsCost: 800, retail: 5.95, category: "ENTREE" },
      { itemName: "Quesadilla", pointsCost: 1200, retail: 9.95, category: "ENTREE" },
      { itemName: "Entree (Burrito / Bowl / Tacos)", pointsCost: 1300, retail: 10.45, category: "ENTREE" },
      { itemName: "Lifestyle Bowl", pointsCost: 1300, retail: 10.95, category: "ENTREE" },
      { itemName: "Entree + Side", pointsCost: 1600, retail: 12.45, category: "COMBO" },
      { itemName: "Double Protein Bowl", pointsCost: 1700, retail: 13.95, category: "ENTREE" },
      { itemName: "Burrito + Chips & Drink", pointsCost: 1900, retail: 14.95, category: "COMBO" },
    ],
  },
  {
    slug: "pancheros",
    name: "Pancheros",
    logo: "/chains/pancheros.svg",
    color: "#ED1C24",
    pointsName: "points",
    websiteUrl: "https://www.pancheros.com",
    appDeepLink: "pancheros://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Cookie", pointsCost: 200, retail: 1.99, category: "DESSERT" },
      { itemName: "Chips & Salsa", pointsCost: 200, retail: 2.49, category: "SIDE" },
      { itemName: "Fountain Drink", pointsCost: 250, retail: 2.49, category: "DRINK" },
      { itemName: "Bottled Drink", pointsCost: 250, retail: 2.79, category: "DRINK" },
      { itemName: "Side of Queso", pointsCost: 350, retail: 2.99, category: "SIDE" },
      { itemName: "Kids Quesadilla", pointsCost: 400, retail: 4.49, category: "ENTREE" },
      { itemName: "Chips & Queso", pointsCost: 450, retail: 4.49, category: "SIDE" },
      { itemName: "Chips & Guac", pointsCost: 450, retail: 4.49, category: "SIDE" },
      { itemName: "Quesadilla", pointsCost: 600, retail: 6.49, category: "ENTREE" },
      { itemName: "Taco Salad", pointsCost: 700, retail: 7.99, category: "ENTREE" },
      { itemName: "Two Tacos", pointsCost: 750, retail: 7.99, category: "ENTREE" },
      { itemName: "Burrito or Bowl", pointsCost: 800, retail: 8.99, category: "ENTREE" },
      { itemName: "Quesarito", pointsCost: 900, retail: 9.49, category: "ENTREE" },
      { itemName: "Burrito + Chips & Drink", pointsCost: 1100, retail: 12.49, category: "COMBO" },
    ],
  },
  {
    slug: "dairyqueen",
    name: "Dairy Queen",
    logo: "/chains/dairyqueen.svg",
    color: "#ED1C24",
    pointsName: "points",
    websiteUrl: "https://www.dairyqueen.com",
    appDeepLink: "dairyqueen://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Small Cone", pointsCost: 250, retail: 2.49, category: "DESSERT" },
      { itemName: "Dilly Bar", pointsCost: 300, retail: 1.99, category: "DESSERT" },
      { itemName: "Small Fries", pointsCost: 300, retail: 2.49, category: "SIDE" },
      { itemName: "Small Sundae", pointsCost: 400, retail: 2.99, category: "DESSERT" },
      { itemName: "Cheeseburger", pointsCost: 600, retail: 3.49, category: "ENTREE" },
      { itemName: "Small Blizzard", pointsCost: 600, retail: 3.99, category: "DESSERT" },
      { itemName: "Chili Cheese Dog", pointsCost: 700, retail: 3.99, category: "ENTREE" },
      { itemName: "4-pc Chicken Strips", pointsCost: 800, retail: 5.49, category: "ENTREE" },
      { itemName: "Medium Blizzard", pointsCost: 800, retail: 4.99, category: "DESSERT" },
      { itemName: "Banana Split", pointsCost: 900, retail: 5.49, category: "DESSERT" },
      { itemName: "1/4 lb GrillBurger", pointsCost: 900, retail: 5.99, category: "ENTREE" },
      { itemName: "Original Cheeseburger Combo", pointsCost: 1000, retail: 6.99, category: "COMBO" },
      { itemName: "Pecan Mudslide Treat", pointsCost: 1000, retail: 5.99, category: "DESSERT" },
      { itemName: "Chicken Strip Basket", pointsCost: 1500, retail: 7.99, category: "COMBO" },
    ],
  },
  {
    slug: "culvers",
    name: "Culver's",
    logo: "/chains/culvers.svg",
    color: "#1B3F8B",
    pointsName: "points",
    websiteUrl: "https://www.culvers.com",
    appDeepLink: "culvers://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Single Scoop Cake Cone", pointsCost: 300, retail: 2.49, category: "DESSERT" },
      { itemName: "Small Crinkle Cut Fries", pointsCost: 350, retail: 2.49, category: "SIDE" },
      { itemName: "Dish of Frozen Custard", pointsCost: 350, retail: 2.79, category: "DESSERT" },
      { itemName: "Cheese Curds (regular)", pointsCost: 600, retail: 5.49, category: "SIDE" },
      { itemName: "Sundae", pointsCost: 600, retail: 3.99, category: "DESSERT" },
      { itemName: "Mini Concrete Mixer", pointsCost: 700, retail: 3.99, category: "DESSERT" },
      { itemName: "Single ButterBurger", pointsCost: 800, retail: 4.79, category: "ENTREE" },
      { itemName: "ButterBurger Cheese", pointsCost: 850, retail: 5.19, category: "ENTREE" },
      { itemName: "Crispy Chicken Sandwich", pointsCost: 900, retail: 6.29, category: "ENTREE" },
      { itemName: "Concrete Mixer", pointsCost: 1000, retail: 5.49, category: "DESSERT" },
      { itemName: "4-pc Chicken Tenders", pointsCost: 1000, retail: 6.99, category: "ENTREE" },
      { itemName: "Double ButterBurger Cheese", pointsCost: 1100, retail: 6.79, category: "ENTREE" },
      { itemName: "Value Basket (burger combo)", pointsCost: 1400, retail: 9.49, category: "COMBO" },
      { itemName: "North Atlantic Cod Dinner", pointsCost: 1600, retail: 11.49, category: "ENTREE" },
    ],
  },
  {
    slug: "jimmyjohns",
    name: "Jimmy John's",
    logo: "/chains/jimmyjohns.svg",
    color: "#ED1C24",
    pointsName: "points",
    websiteUrl: "https://www.jimmyjohns.com",
    appDeepLink: "jimmyjohns://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Jumbo Kosher Dill Pickle", pointsCost: 150, retail: 1.49, category: "SIDE" },
      { itemName: "Bag of Chips", pointsCost: 200, retail: 1.79, category: "SIDE" },
      { itemName: "Chocolate Chunk Cookie", pointsCost: 250, retail: 2.19, category: "DESSERT" },
      { itemName: "Fountain Drink", pointsCost: 300, retail: 2.29, category: "DRINK" },
      { itemName: "Little John", pointsCost: 450, retail: 3.99, category: "ENTREE" },
      { itemName: "Chips & Cookie Bundle", pointsCost: 450, retail: 3.99, category: "SIDE" },
      { itemName: "Slim Sandwich", pointsCost: 500, retail: 5.49, category: "ENTREE" },
      { itemName: "Mini Jimmy (Kids)", pointsCost: 600, retail: 5.49, category: "ENTREE" },
      { itemName: "The Original (8\" Sub)", pointsCost: 1000, retail: 8.49, category: "ENTREE" },
      { itemName: "Unwich (Lettuce Wrap)", pointsCost: 1000, retail: 8.49, category: "ENTREE" },
      { itemName: "Combo (8\" + chips + drink)", pointsCost: 1300, retail: 11.49, category: "COMBO" },
      { itemName: "Giant 16\" Club", pointsCost: 1600, retail: 13.99, category: "ENTREE" },
      { itemName: "16\" Party Sub", pointsCost: 2500, retail: 21.99, category: "ENTREE" },
    ],
  },
  {
    slug: "buffalowildwings",
    name: "Buffalo Wild Wings",
    logo: "/chains/buffalowildwings.svg",
    color: "#FAB31E",
    pointsName: "points",
    websiteUrl: "https://www.buffalowildwings.com",
    appDeepLink: "bww://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Fountain Drink", pointsCost: 250, retail: 2.99, category: "DRINK" },
      { itemName: "Side of Fries", pointsCost: 300, retail: 3.99, category: "SIDE" },
      { itemName: "Snack-size Wings (5 pc)", pointsCost: 500, retail: 6.49, category: "ENTREE" },
      { itemName: "Mozzarella Sticks", pointsCost: 600, retail: 7.49, category: "SIDE" },
      { itemName: "Cheesecake", pointsCost: 600, retail: 6.49, category: "DESSERT" },
      { itemName: "Loaded Chips", pointsCost: 700, retail: 8.49, category: "SIDE" },
      { itemName: "Buffalo Mac & Cheese", pointsCost: 700, retail: 7.99, category: "SIDE" },
      { itemName: "Street Tacos", pointsCost: 800, retail: 8.99, category: "ENTREE" },
      { itemName: "Chicken Sandwich", pointsCost: 900, retail: 9.99, category: "ENTREE" },
      { itemName: "Ultimate Nachos", pointsCost: 900, retail: 10.49, category: "SIDE" },
      { itemName: "Boneless Wings (10 pc)", pointsCost: 1200, retail: 13.49, category: "ENTREE" },
      { itemName: "Traditional Wings (10 pc)", pointsCost: 1500, retail: 16.99, category: "ENTREE" },
      { itemName: "Wings + Fries Combo", pointsCost: 1800, retail: 18.99, category: "COMBO" },
      { itemName: "Traditional Wings (15 pc)", pointsCost: 2200, retail: 22.99, category: "ENTREE" },
    ],
  },
  {
    slug: "kfc",
    name: "KFC",
    logo: "/chains/kfc.svg",
    color: "#F40027",
    pointsName: "points",
    websiteUrl: "https://www.kfc.com",
    appDeepLink: "kfc://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Biscuit", pointsCost: 150, retail: 1.29, category: "SIDE" },
      { itemName: "Cookie", pointsCost: 200, retail: 1.49, category: "DESSERT" },
      { itemName: "Individual Side", pointsCost: 300, retail: 2.99, category: "SIDE" },
      { itemName: "Chicken Little Sandwich", pointsCost: 400, retail: 3.49, category: "ENTREE" },
      { itemName: "Large Side", pointsCost: 450, retail: 3.99, category: "SIDE" },
      { itemName: "8-pc Nuggets", pointsCost: 500, retail: 4.99, category: "ENTREE" },
      { itemName: "Chicken Sandwich", pointsCost: 600, retail: 4.99, category: "ENTREE" },
      { itemName: "3-pc Tenders", pointsCost: 600, retail: 5.49, category: "ENTREE" },
      { itemName: "Mac & Cheese Bowl", pointsCost: 650, retail: 5.49, category: "ENTREE" },
      { itemName: "Famous Bowl", pointsCost: 700, retail: 5.99, category: "ENTREE" },
      { itemName: "Pot Pie", pointsCost: 700, retail: 5.49, category: "ENTREE" },
      { itemName: "2-pc Chicken Meal", pointsCost: 900, retail: 7.49, category: "COMBO" },
      { itemName: "Fill Up Box", pointsCost: 1100, retail: 8.99, category: "COMBO" },
      { itemName: "8-pc Bucket", pointsCost: 1500, retail: 14.99, category: "ENTREE" },
      { itemName: "12-pc Bucket Meal", pointsCost: 2000, retail: 21.99, category: "COMBO" },
    ],
  },
  {
    slug: "pandaexpress",
    name: "Panda Express",
    logo: "/chains/pandaexpress.svg",
    color: "#D81E05",
    pointsName: "points",
    websiteUrl: "https://www.pandaexpress.com",
    appDeepLink: "pandaexpress://",
    scrapingEnabled: true,
    redemptions: [
      { itemName: "Fortune Cookies (pack)", pointsCost: 200, retail: 0.99, category: "DESSERT" },
      { itemName: "Chicken Egg Roll", pointsCost: 400, retail: 1.99, category: "SIDE" },
      { itemName: "Fountain Drink", pointsCost: 400, retail: 2.59, category: "DRINK" },
      { itemName: "Veggie Spring Rolls (2 pc)", pointsCost: 500, retail: 2.49, category: "SIDE" },
      { itemName: "Apple Pie Roll", pointsCost: 500, retail: 1.99, category: "DESSERT" },
      { itemName: "Hot & Sour Soup", pointsCost: 500, retail: 2.49, category: "SIDE" },
      { itemName: "Cream Cheese Rangoon (3 pc)", pointsCost: 600, retail: 2.99, category: "SIDE" },
      { itemName: "Small Side (Fried Rice or Chow Mein)", pointsCost: 600, retail: 4.40, category: "SIDE" },
      { itemName: "A La Carte Entree", pointsCost: 1500, retail: 5.99, category: "ENTREE" },
      { itemName: "Premium Entree (Honey Walnut Shrimp)", pointsCost: 2000, retail: 6.99, category: "ENTREE" },
      { itemName: "Bowl (1 side + 1 entree)", pointsCost: 2200, retail: 8.40, category: "COMBO" },
      { itemName: "Plate (1 side + 2 entrees)", pointsCost: 3000, retail: 10.40, category: "COMBO" },
      { itemName: "Bigger Plate (1 side + 3 entrees)", pointsCost: 3800, retail: 12.40, category: "COMBO" },
    ],
  },
];

async function main() {
  console.log("Seeding chains and redemption options...");

  for (const c of CHAINS) {
    const chain = await prisma.chain.upsert({
      where: { slug: c.slug },
      update: {
        name: c.name,
        logo: c.logo,
        color: c.color,
        pointsName: c.pointsName,
        websiteUrl: c.websiteUrl,
        appDeepLink: c.appDeepLink,
        scrapingEnabled: c.scrapingEnabled,
      },
      create: {
        slug: c.slug,
        name: c.name,
        logo: c.logo,
        color: c.color,
        pointsName: c.pointsName,
        websiteUrl: c.websiteUrl,
        appDeepLink: c.appDeepLink,
        scrapingEnabled: c.scrapingEnabled,
      },
    });

    await prisma.redemptionOption.deleteMany({ where: { chainId: chain.id } });

    await prisma.redemptionOption.createMany({
      data: c.redemptions.map((r) => ({
        chainId: chain.id,
        itemName: r.itemName,
        pointsCost: r.pointsCost,
        estimatedRetailPrice: r.retail,
        centsPerPoint: centsPerPoint(r.retail, r.pointsCost),
        category: r.category,
        isAvailable: true,
        lastVerified: new Date(),
      })),
    });

    const best = [...c.redemptions]
      .map((r) => ({ ...r, cpp: centsPerPoint(r.retail, r.pointsCost) }))
      .sort((a, b) => b.cpp - a.cpp)[0];

    console.log(
      `  ✓ ${c.name.padEnd(14)} ${c.redemptions.length} redemptions   best: ${best.itemName} @ ${best.cpp.toFixed(3)} ¢/${c.pointsName.replace(/s$/, "")}`,
    );
  }

  console.log(`\nDone — seeded ${CHAINS.length} chains.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
